locations_list = [
    "JP Nagar Phase 1",
    "other",
    "Kannur on Thanisandra Main Road",
    "Kengeri",
    "Horamavu",
    "Thanisandra",
    "Ramamurthy Nagar",
    "Whitefield Hope Farm Junction",
    "Electronic City Phase 1",
    "Yelahanka",
    "Anjanapura",
    "Jalahalli",
    "Kasavanahalli",
    "Bommasandra",
    "Bellandur",
    "RR Nagar",
    "Begur",
    "Hosa Road",
    "Kadugodi",
    "Jakkur",
    "Krishnarajapura",
    "Banashankari",
    "Nelamangala",
    "Attibele",
    "ITPL",
    "Varthur",
    "Electronic City Phase 2",
    "Anekal City",
    "Sarjapur",
    "Hebbal",
    "Budigere Cross",
    "Bommanahalli",
    "Narayanapura on Hennur Main Road",
    "Sarjapur Road Wipro To Railway Crossing",
    "Talaghattapura",
    "Kumbalgodu",
    "Carmelaram",
    "Uttarahalli",
    "Avalahalli Off Sarjapur Road",
    "JP Nagar Phase 7",
    "Subramanyapura",
    "JP Nagar Phase 4",
    "JP Nagar Phase 8",
    "Chandapura",
    "JP Nagar Phase 3",
    "Gottigere",
    "Kanakapura Road Beyond Nice Ring Road",
    "Harlur",
    "Konanakunte",
    "Richmond Town",
    "Devanahalli",
    "Kumaraswamy Layout",
    "Hennur",
    "Rajajinagar",
    "Yeshwantpur",
    "Kalyan Nagar",
    "Uttarahalli Main Road",
    "sarjapura attibele road",
]

list_of_selected_locations = [
    "Location_Anjanapura",
    "Location_Attibele",
    "Location_Avalahalli Off Sarjapur Road",
    "Location_Banashankari",
    "Location_Begur",
    "Location_Bellandur",
    "Location_Bommanahalli",
    "Location_Bommasandra",
    "Location_Budigere Cross",
    "Location_Carmelaram",
    "Location_Chandapura",
    "Location_Devanahalli",
    "Location_Electronic City Phase 1",
    "Location_Electronic City Phase 2",
    "Location_Gottigere",
    "Location_Harlur",
    "Location_Hebbal",
    "Location_Hennur",
    "Location_Horamavu",
    "Location_Hosa Road",
    "Location_ITPL",
    "Location_JP Nagar Phase 1",
    "Location_JP Nagar Phase 3",
    "Location_JP Nagar Phase 4",
    "Location_JP Nagar Phase 7",
    "Location_JP Nagar Phase 8",
    "Location_Jakkur",
    "Location_Jalahalli",
    "Location_Kadugodi",
    "Location_Kalyan Nagar",
    "Location_Kanakapura Road Beyond Nice Ring Road",
    "Location_Kannur on Thanisandra Main Road",
    "Location_Kasavanahalli",
    "Location_Kengeri",
    "Location_Konanakunte",
    "Location_Krishnarajapura",
    "Location_Kumaraswamy Layout",
    "Location_Kumbalgodu",
    "Location_Narayanapura on Hennur Main Road",
    "Location_Nelamangala",
    "Location_RR Nagar",
    "Location_Rajajinagar",
    "Location_Ramamurthy Nagar",
    "Location_Richmond Town",
    "Location_Sarjapur",
    "Location_Sarjapur Road Wipro To Railway Crossing",
    "Location_Subramanyapura",
    "Location_Talaghattapura",
    "Location_Thanisandra",
    "Location_Uttarahalli",
    "Location_Uttarahalli Main Road",
    "Location_Varthur",
    "Location_Whitefield Hope Farm Junction",
    "Location_Yelahanka",
    "Location_Yeshwantpur",
    "Location_other",
    "Location_sarjapura attibele road",
]
